Algoritmo "Par ou Ímpar"
// 
//  
// Descrição   : Faça um programa que leia um número e diga se ele é par OU ímpar.

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2025
Var
// Seção de Declarações das variáveis 
impar_ou_par: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Favor digite um numero:")
leia(impar_ou_par)
se (impar_ou_par % 2 = 0) então
escreval("O numero que você digitou é pae")
senao
escreval("O numero que vocÊ digitou é impar")
fimse

Fimalgoritmo