Algoritmo "Senha de Acesso"
//  
//  
// 
//  
// Descrição   : O programa deve pedir uma senha.
// Se a senha for 1234, escreva "Acesso Permitido".
//Caso contrário, escreva "Acesso Negado".

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2025
Var
// Seção de Declarações das variáveis 
senha: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Favor digite a sua senha numerica contendo 4 caracteres:")
leia(senha)
se senha=1234 entao
escreval("Acesso Permitido")
senao
escreval("Acesso Negado")
fimse


Fimalgoritmo