Algoritmo "Triângulo"
// 
//  
// Descrição   : Peça 3 lados de um triângulo.
//Se (a + b > c) E (a + c > b) E (b + c > a), escreva "É um triângulo".
//Caso contrário, escreva "Não é um triângulo".

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/09/2025
Var
// Seção de Declarações das variáveis 
a, b, c: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Favor digite o tamanho do lado A:")
leia(a)
escreval("Favor digite o tamanho do lado B:")
leia(b)
escreval("Favor digite o tamanho do lado C:")
leia(c)
se (a + b > c) e (a + c > b) e (b + c > a) então
escreval("A sua fugura é um triângulo")
senao
escreval("A sua fugura é um triângulo")
fimse




Fimalgoritmo